# Generated by Django 5.1.4 on 2024-12-09 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, default='Others', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.category'),
        ),
    ]
